### ISSUE TITLE
Mejorar práctica de fonts en archivo CSS

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#1]
https://github.com/sephirot94/Universys_WebPage/blob/8e2ece0badad9247fb878321c728d167de3491b7/Carreras/css/carrera.css#L6

No todos los browsers tienen todas las fonts, por lo que es buena práctica indicar alternativas en caso de que la deseada no esté presente.

**Comment by Nachot93** [comment]
Se agregaron Arial y Times New Roman:

`font-family: 'Roboto', 'Arial', 'Times New Roman', sans-serif;`
