### ISSUE TITLE
Código comentado no debería estar presente en un branch común

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#10]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/html/register.html#L18

En verdad, no es buena práctica jamás tener código comentado. Pero si llega a estar, no debería ser en un branch común, sino en uno personal o al menos no de integración.

**Comment by Nachot93** [comment]
Resuelto!
