### ISSUE TITLE
Action incorrecta

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#13]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/html/registerCatedras.html#L37

Parece como que el valor que pusieron aquí ("post") debería ser del atributo "method", no "action". "action" seguramente ejecutará algún Javascript.

**Comment by Nachot93** [comment]
Arreglado!
