### ISSUE TITLE
Caracter incorrecto

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#16]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/html/reiniciarContrase%C3%B1a.html#L4

La letra "ñ" debería estar encodeada en HTML; en este caso, "& ntilde ;".

**Comment by Nachot93** [comment]
Arreglado tambien!
