### ISSUE TITLE
Más caracteres incorrectos

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#17]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/html/reiniciarContrase%C3%B1a.html#L35

Hay una 'ó presente, y más abajo más 'ñ' y otros caracteres con tilde.

**Comment by Nachot93** [comment]
Arreglado tambien!
