### ISSUE TITLE
Peligroso nombre de archivo

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#18]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/html/reiniciarContrase%C3%B1a.html#L1

El nombre de archivo "registrarContraseña.html" es riesgoso; puede tener problemas en algún servidor en particular, o con algún browser, o combinación de ambos.
Se recomienda cambiarlo por "registrarPassword.html" o "registrarContrasena.html".

**Comment by Nachot93** [comment]
Arreglado, se cambió por reiniciarContrasena.html
