### ISSUE TITLE
No respeta formato acordado y documentado

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#21]
https://github.com/sephirot94/Universys_WebPage/blob/08940d8c36ee91d87b13c11f7a44f092b5bd5fc4/js/register.js#L77

La fecha no es simulada con el formato acordado con el equipo de desarrollo de backend.

**Comment by sephirot94** [comment]
fix commit 076c1484958c9b0f61ddf1717eb25092a284f817
