### ISSUE TITLE
Reflexión sobre colores nombrados en lugar de código RGB

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#3]
https://github.com/sephirot94/Universys_WebPage/blob/8e2ece0badad9247fb878321c728d167de3491b7/css/login.css#L7

No es necesario que lo cambien, pero piensen que usar colores por su nombre puede provocar que el color difiera dependiendo de la implementación de cada buscador. Usando el código RGB se asegura que el color sea el mismo en todas partes.

**Comment by Nachot93** [comment]
Listo, pasados todos los colores a formato RGB
