### ISSUE TITLE
Tags mal cerrados

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#5]
https://github.com/sephirot94/Universys_WebPage/blob/8e2ece0badad9247fb878321c728d167de3491b7/html/carreras.html#L4

Veo que los tags meta, link y algún que otro tag script inline no tienen el cierre estándar. Es decir, en lugar de:
`<link src="fruta">`
Debería ser:
`<link src="fruta" />`

**Comment by Nachot93** [comment]
El nuevo estandar lo permite
