### ISSUE TITLE
Caracteres inválidos

### ISSUE THREAD

**Issue by didierrenardub** [sephirot94/Universys_WebPage#6]
https://github.com/sephirot94/Universys_WebPage/blob/8e2ece0badad9247fb878321c728d167de3491b7/html/carreras.html#L36

Todos los caracteres con tilde, así como determinados caracteres especiales, deberían ir en la notación HTML para evitar problemas de rendering. En este caso, por ejemplo, habría que reemplazar la 'ó' por '& oacute ;' (escrito todo junto, sólo que GitHub lo convierte en el caracter en cuestión).

**Comment by Nachot93** [comment]
Arreglado!
